### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by k1ng440** [DataDog/dd-trace-go#399] opened 2019-02-22 22:21 UTC
```
fatal error: concurrent map writes

goroutine 4592 [running]:
runtime.throw(0x11f9fb8, 0x15)
     /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc0000c1b10 sp=0xc0000c1ae0 pc=0x42c252
runtime.mapassign_faststr(0x1096f20, 0xc000647410, 0x11f6f64, 0x12, 0x13)
     /usr/local/go/src/runtime/map_faststr.go:199 +0x3da fp=0xc0000c1b78 sp=0xc0000c1b10 pc=0x4128ea
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.TextMapCarrier.Set(0xc000647410, 0x11f6f64, 0x12, 0xc0003b83a0, 0x13)
     /e/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.9.0/ddtrace/tracer/textmap.go:44 +0x4b fp=0xc0000c1bb0 sp=0xc0000c1b78 pc=0x9b714b
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*propagator).injectTextMap(0xc000184140, 0x1383a00, 0xc00074a6c0, 0x7f6cfaf319e8, 0xc000647410, 0xc0000c1c01, 0x42afb2)
     /e/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.9.0/ddtrace/tracer/textmap.go:139 +0xcf fp=0xc0000c1c78 sp=0xc0000c1bb0 pc=0x9b743f
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*propagator).Inject(0xc000184140, 0x1383a00, 0xc00074a6c0, 0x1096f20, 0xc000647410, 0x1237768, 0x1ccd210)
     /e/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.9.0/ddtrace/tracer/textmap.go:127 +0x98 fp=0xc0000c1cc0 sp=0xc0000c1c78 pc=0x9b7348
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.(*tracer).Inject(0xc000038900, 0x1383a00, 0xc00074a6c0, 0x1096f20, 0xc000647410, 0xc000fd0460, 0xc0003909a0)
     /e/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.9.0/ddtrace/tracer/tracer.go:293 +0x5f fp=0xc0000c1d08 sp=0xc0000c1cc0 pc=0x9b8f7f
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer.Inject(0x1383a00, 0xc00074a6c0, 0x1096f20, 0xc000647410, 0xc000647560, 0x4)
     /e/go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.9.0/ddtrace/tracer/tracer.go:100 +0x5d fp=0xc0000c1d50 sp=0xc0000c1d08 pc=0x9b7c0d
github.com/coinread/microservice/datadog.(*tracker).StartSpanFromContext(0xc0002f04d0, 0x1386e80, 0xc0006477a0, 0xc0002f04d0, 0xc0002f0380)
     /e/go/pkg/mod/github.com/coinread/microservice@v1.5.2/datadog/tracker.go:78 +0x249 fp=0xc0000c1df0 sp=0xc0000c1d50 pc=0xb53bf9
github.com/coinread/microservice/datadog.(*ddWrapper).Call(0xc000174730, 0x1386e80, 0xc000274c30, 0x138c4c0, 0xc0002f0380, 0x1151540, 0xc0003afec0, 0x0, 0x0, 0x0, ...)
     /e/go/pkg/mod/github.com/coinread/microservice@v1.5.2/datadog/datadog.go:26 +0xa7 fp=0xc0000c1e68 sp=0xc0000c1df0 pc=0xb53477
github.com/coinread/ticker-srv/proto/ticker-archive-srv/ticker-archive.(*tickerArchiveService).GetHighLow(0xc000172a00, 0x1386e80, 0xc000274c30, 0xc0009c7db0, 0x0, 0x0, 0x0, 0x1105060, 0x1, 0xc000274930)
     /e/go/src/github.com/coinread/ticker-srv/proto/ticker-archive-srv/ticker-archive/ticker-archive.micro.go:156 +0x13b fp=0xc0000c1ef0 sp=0xc0000c1e68 pc=0xb45fdb
github.com/coinread/ticker-srv/subscriber.(*TickerMultiCreate).getHighLow.func1(0xc000028580, 0x1386e80, 0xc000274c30, 0x0, 0xed4026adb, 0x1caed20, 0xc000fd4c60)
     /e/go/src/github.com/coinread/ticker-srv/subscriber/ticker_multi.go:111 +0x14d fp=0xc0000c1fa8 sp=0xc0000c1ef0 pc=0xb4ee8d
runtime.goexit()
     /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000c1fb0 sp=0xc0000c1fa8 pc=0x45a511
created by github.com/coinread/ticker-srv/subscriber.(*TickerMultiCreate).getHighLow
     /e/go/src/github.com/coinread/ticker-srv/subscriber/ticker_multi.go:109 +0xa3
```

**Comment by gbbr** [comment] 2019-02-23 08:57
Do you have a code sample to reproduce this?

**Comment by k1ng440** [comment] 2019-02-23 20:26
Hello,
Yes its located at https://github.com/coinread/datadog-micro

please run `go test -race`

**Comment by gbbr** [comment] 2019-02-25 09:54
I can not run that, some code (such as `coinread/log`) can not be downloaded because it's private.

**Comment by k1ng440** [comment] 2019-02-25 14:13
Hello @gbbr 
please try again, i have removed all private repo

**Comment by gbbr** [comment] 2019-02-26 09:42
The race condition is in your test code. You are [extracting](https://github.com/coinread/datadog-micro/blob/0ec63f4ff20302e53b5dee8d4249392e79644a1c/helper.go#L20) and [injecting](https://github.com/coinread/datadog-micro/blob/0ec63f4ff20302e53b5dee8d4249392e79644a1c/helper.go#L26) into [the same context](https://github.com/coinread/datadog-micro/blob/0ec63f4ff20302e53b5dee8d4249392e79644a1c/datadog_test.go#L192) concurrently. There are other additional races occurring too. I'd also recommend using a `sync.WaitGroup` to wait for all goroutines to finish in your test. That's another race condition.

In the future, when opening issues, please provide full context and reproduction steps. It helps us reproduce it. Simply pasting an error into a Github issue makes it difficult to do so.

**Comment by k1ng440** [comment] 2019-03-06 00:44
Hello,
I am sorry i have been away.

Yes i am extracting and injecting but that seems to be very wrong. i cant figure out any other way to do this package. 

can we implement something like this?
https://github.com/micro/go-plugins/blob/master/wrapper/trace/opencensus/opencensus.go#L29
https://godoc.org/go.opencensus.io/trace/propagation


ps i have updated the code to use WaitGroup. 
https://github.com/coinread/datadog-micro/blob/master/datadog_test.go#L189


Looking forward to your suggestion

**Comment by gbbr** [comment] 2019-03-07 06:00
I think it's no problem to implement what you are trying to do. Can you explain very simply, in words, what you are trying to achieve. Let's start small before we get to actual code.

**Comment by k1ng440** [comment] 2019-03-07 08:16
Hello,
We could use the Binary Propagation like the opentracing so its more concurrent safe since map[string]string is not concurrent safe without the mutex

i have found a opentracing library called `lightstep-tracer-go`, they have created a binary propagation. please visit 
https://github.com/lightstep/lightstep-tracer-go/blob/master/propagation_binary.go

**Comment by gbbr** [comment] 2019-03-07 14:27
Since you've opened https://github.com/DataDog/dd-trace-go/issues/406 and there is no race condition, I'm closing this and moving the discussion there.

**Closed by gbbr** 2019-03-07 14:27 UTC
