### ISSUE TITLE
opentracing: config and DefaultTracer

### ISSUE THREAD

**Issue by pierrre** [DataDog/dd-trace-go#170] opened 2018-01-31 16:27 UTC
I'm trying to use the opentracing "bridge" + integrations (like gorilla/mux).
I'm initializing my code with the example from the front page https://github.com/DataDog/dd-trace-go .
In my configuration, I set some `GlobalTags`: `env` and `version` (version of my app).

It works properly if I start my own span with the official opentracing lib.
I see my tags in my spans.

However, if I use the gorilla/mux integration, it doesn't work as expected.
I don't see the tags/meta or the service name in the spans created by gorilla/mux.
(I create the router with https://github.com/DataDog/dd-trace-go/blob/6ba9d7ab13ac75d2b739571566f30e4d3ebe39e9/contrib/gorilla/mux/mux.go#L22 )

I think that the issue is somewhere here https://github.com/DataDog/dd-trace-go/blob/6ba9d7ab13ac75d2b739571566f30e4d3ebe39e9/opentracing/tracer.go#L151-L178
`ddtrace.DefaultTracer` is initialized, but the meta/tags and service name are not copied.

For now I will fix this on my side and initializes `DefaultTracer` with my own config.

**Comment by pierrre** [comment] 2018-01-31 16:44
Same issue fore the "enabled" config.
It's not copied properly.

**Comment by gbbr** [comment] 2018-01-31 17:05
I can see how this can be confusing. The integrations (`contrib/*`) are not yet migrated over to use OpenTracing. We are planning to do this for 0.7.0, which will be all OpenTracing compatible. Until then, please hold tight 😊

**Comment by pierrre** [comment] 2018-01-31 17:06
OK I understand, thanks.

**Comment by pierrre** [comment] 2018-02-01 13:18
> The integrations (contrib/*) are not yet migrated over to use OpenTracing

Indeed it doesn't work currently.
In my code, I do this:
- create a root span with the gorilla/mux integration
- create new child span from request's context with open tracing

The result:
- in https://app.datadoghq.com/apm/services I only see the spans created by gorilla/mux, and the child span are not there
- in https://app.datadoghq.com/apm/search I see all span (gorilla/mux + child)

If I understand correctly, the issue is that the span types are not compatible, and the parent span is not found from context (different key probably).

I see several solutions for me:
- wait for the integration migration (when will it be available ?)
- build my own integration compatible with opentracing
- contribute to the existing integration (it should be very similar to my own code)

I'd like to contribute, but I don't know what are your plans.

**Comment by pierrre** [comment] 2018-02-01 13:19
PS: if I use only the opentracing span as root, there is no issue.

**Comment by gbbr** [comment] 2018-02-01 13:51
> wait for the integration migration (when will it be available ?)

I am working on this _as we speak_ and is my main priority at the moment. We plan to release this with 0.7.0 once we dog food it internally. You are welcome to help with that if you want, at your own risk :-)

> contribute to the existing integration (it should be very similar to my own code)

I would not advise to do this now, as it will result in terrible merge conflicts.

> I'd like to contribute, but I don't know what are your plans.

I would be very happy to have you as a contributor. I think that after we finish this piece of work, contributing to this library should be much easier and straight-forward. I am also glad to hear that you have this intention, your help would be most welcomed.

The best thing you can do for now is to be patient and give us the time to do this. I reckon in a couple of weeks it will be ready. If this is urgent for you, of course you can build your own integration in the mean time. Contributing now is not a very good time because this switch affects the entire codebase.

I am happy to answer any more questions you might have. You are also welcome to reach me on our Public Slack if you want.

**Comment by pierrre** [comment] 2018-02-01 15:02
quick and dirty hack https://gist.github.com/pierrre/d6f86351ce384a30b548c8ef2ecb6ebf

**Comment by gbbr** [comment] 2018-02-06 09:17
@pierrre I will close this as a duplicate of https://github.com/DataDog/dd-trace-go/issues/175 - I hope you don't mind. If that issue doesn't cover it or if this is for something else, then please feel free to re-open.

**Closed by gbbr** 2018-02-06 09:17 UTC
Labels: bug, integrations

**Comment by pierrre** [comment] 2018-02-06 09:51
ok, no problem
