### ISSUE TITLE
opentracing: AppType not set from opentracing config

### ISSUE THREAD

**Issue by hamiltop** [DataDog/dd-trace-go#185] opened 2018-02-21 23:30 UTC
There's no way to set the AppType from the opentracing tracer config.

It'd probably be easy enough to add the full service description to the config.

**Comment by gbbr** [comment] 2018-02-22 07:01
You can set this by setting the `span.type` tag. We will update the documentation soon.
```go
span.SetTag("span.type", "web")
```

I will close the issue. Feel free to re-open if the problem persists.

**Comment by hamiltop** [comment] 2018-02-22 17:39
That will tag the span as `web` but the service still shows up in the UI as `Custom`.

**Comment by gbbr** [comment] 2018-02-22 17:44
We are working on a new release candidate, this issue should be resolved there. Re-opening until we can confirm that.

**Comment by palazzem** [comment] 2018-02-26 23:00
Hello @hamiltop! actually if you're using an Agent version greater than 5.21.1, it's enough that you set the `span.type = web`. If it's not working and you're doing both actions, it's probably related to an issue we had before (ref: https://github.com/DataDog/dd-trace-go/issues/176#issuecomment-364126596). If this is the case, we can double check and update the priority of reported values in our backend, so you don't need to wait for our release candidate to fix the problem.

Let me know if the problem is still there and you're using an updated version of the Datadog Agent. Thank you very much!

**Comment by russellballestrini** [comment] 2018-02-27 20:25
@palazzem we use Ubuntu 14.04, and it seems the newest version in the datadog Apt repo is apt: `datadog-agent=1:5.4.2-1` not `datadog-agent=1:5.21.1`.

Does this version include the fix?

**Comment by gbbr** [comment] 2018-05-08 09:39
I am closing this, since the above suggestion should work. If it's still a problem, don't hesitate to re-open or ping us.

**Closed by gbbr** 2018-05-08 09:39 UTC
Labels: needs-investigation
