### ISSUE TITLE
question: opentracing.SpanFromContext(request.Context()) returns nil inside a datadog span

### ISSUE THREAD

**Issue by davidalpert** [DataDog/dd-trace-go#813] opened 2021-01-11 16:43 UTC
I seem unable to instrument code with the opentracing libraries and tie them to the datadog tracer.  all the code samples I can find suggest that I must use the datadog tracing libraries but I thought that datadog supports the opentracing pattern...

in our `main` package we import the `ddtrace/tracer` and the `contrib/gorilla/mux` handler:
```go
package main

import (
	"gopkg.in/DataDog/dd-trace-go.v1/contrib/gorilla/mux"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

func main() {
	// configure datadog trace agent
	tracer.Start()
	defer tracer.Stop()
	
        router := mux.NewRouter() // should be a datadog gorilla router, trace-enabled
	router.HandleFunc("/test", testpackage.HandleWebRequest)
	server := &http.Server{
		Addr:    fmt.Sprintf(":%d", port),
		Handler: router,
	}

	server.ListenAndServe()
}
```

in another package we import the opentracing libraries and try to get access to the current span from the web request `context.Context`:
```go
package testpackage

import (
	"github.com/opentracing/opentracing-go"
	"github.com/opentracing/opentracing-go/ext"
)

func HandleWebRequest(writer http.ResponseWriter, request *http.Request) {
	span := opentracing.SpanFromContext(request.Context())
	defer span.Finish()
	
	// handling logic continues, but span is nil
}
```

Am I trying to do something unsupported?

How would one integrate opentracing-instrumented code in a datadog tracer-instrumented app?

**Comment by davidalpert** [comment] 2021-01-11 16:51
maybe this is what I was missing?
- https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace#example-package-Opentracing

**Comment by davidalpert** [comment] 2021-01-11 17:00
added:
```go
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
```
and now initialized the tracer like this:
```go
	// Start a Datadog tracer, optionally providing a set of options,
	// returning an opentracing.Tracer which wraps it.
	t := opentracer.New(
		// configure datadog trace agent with our apex logging adapter
		tracer.WithLogger(adapters.DDTraceLogger{}),
		)
	defer tracer.Stop() // important for data integrity (flushes any leftovers)

	// Use it with the Opentracing API. The (already started) Datadog tracer
	// may be used in parallel with the Opentracing API if desired.
	opentracing.SetGlobalTracer(t)
```
and the `span` returned from `opentraging.SpanFromContext(request.Context())` is still `nil`

**Comment by davidalpert** [comment] 2021-01-11 17:50
looks like I was able to create a new opentracing span as a child of the datadog tracing span when I first start handling the web request, and after that subsequent use of the opentracing methods link up to the trace as expected:

```go
func (c *Controller) ListAvailableVersions(writer http.ResponseWriter, request *http.Request) {
	ddSpan, _ :=  tracer.SpanFromContext(request.Context())
	span, spanCtx := opentracing.StartSpanFromContext(request.Context(), "ListAvailableVersions", opentracing.ChildOf(ddSpan.Context()))

        // span is now non-nil, 
        // passing spanCtx to child methods allows them to call opentracingStartSpanFromContext(spanCtx) and get a child span linked up to the same trace.
}
```

in the example above the `ListAvailableVersions` opentracing span doubles up on the `GET /path/to/resource` span created by the datadog tracer.

- is it expected that I have to explicitly create a duplicate span for this handlefunc in order to properly associate opentracing child spans with the original datadog trace?

**Comment by knusbaum** [comment] 2021-01-13 19:10
Hi @davidalpert. Sorry it took me a bit to respond. I wanted to dig through the code thoroughly to make sure I could give you a complete response.

### Problem Details
Our `opentracing` client allows users to use the datadog tracer as an opentracing tracer, meaning that the opentracing API can be used with the datadog tracer. However, it's unfortunately not currently seamless to use both the datadog API and the opentracing API together ( i.e. using datadog integrations together with the opentracing API).

Currently, the tracer package's `StartSpan` function will forward the call to whatever tracer is running:
https://github.com/DataDog/dd-trace-go/blob/3ed2a2784fd7adb414f2f47dbb6b6a1d301cdf8c/ddtrace/tracer/tracer.go#L112-L116

So if you are running our opentracer ([gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/opentracer)) as it appears you have done, our integrations should create opentracing-compatible spans. This is good.

Where we run into trouble is in the context handling. While `StartSpan` is forwarded to whatever tracer is running, the [context functions](https://github.com/DataDog/dd-trace-go/blob/3ed2a2784fd7adb414f2f47dbb6b6a1d301cdf8c/ddtrace/tracer/context.go#L19-L51) (`ContextWithSpan`, `SpanFromContext`, and `StartSpanFromContext`) all assume that we are using the datadog tracer, and so use [our own key](https://github.com/DataDog/dd-trace-go/blob/3ed2a2784fd7adb414f2f47dbb6b6a1d301cdf8c/ddtrace/tracer/context.go#L17) to store the span in the context. We would need to store the span in the context differently so that opentracing would know where to find it.

### Workaround
What you are doing works, but also means you have duplicate spans. Instead, you should be able to do the following workaround:
```
	spanCtx := request.Context()
	ddSpan, _ := tracer.SpanFromContext(spanCtx)
	if otSpan, ok := ddSpan.(opentracing.Span); ok {
		spanCtx = opentracing.ContextWithSpan(spanCtx, otSpan)
	}
```
This pulls the span from the context and re-injects it into the context as an opentracing span.
The interface conversion is necessary since it's possible that another tracer was installed, in which case the span will not be an `opentracing.Span` and the conversion will fail. In that case the original `request.Context()` will be used.

I will add a proposal ticket to make the context functions tracer-specific, which should remove the need for this workaround. Please let me know if this solution works for you in the meantime.

**Comment by nishkala-square** [comment] 2021-02-18 03:05
Hi, I'm also seeing a similar issue. I'm attempting to use some of the datadog integrations along with opentracing in the app. I believe it should work based on this comment: https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/opentracer/tracer.go#L17

The issue I'm having is that none of the dd-trace/contrib wrappers are being connected to the running span. I have not been able to get it working using the workaround, since I don't always have access to the internals of where the span starts. 

Is there any further news on this getting added to the package?

**Comment by gbbr** [comment] 2021-02-18 10:04
Mixing both Opentracing and Datadog spans is not supported and expected to work in dd-trace-go. You have to chose either one or the other. There are many internals specific to each that one might have and the other not.

**Comment by nishkala-square** [comment] 2021-02-18 15:20
My understanding of the comment I linked to in the datadog file was that we should be able to use them interchangably and some of the official datadog documentation seems to agree. https://docs.datadoghq.com/tracing/setup_overview/open_standards/go/

> Note: Using the OpenTracing API in parallel with the regular API or Datadog integrations is fully supported. Under the hood, all of them make use of the same tracer. See the API documentation for more examples and details.

Has that stance changed?

**Comment by gbbr** [comment] 2021-02-19 11:15
Unfortunately it's not supported. Never was. I'm not sure why that is in the public documentation. I will look into it. It was always in our readme with the warning ⚠️ emoji. I'm sorry for the confusion.

**Comment by shannontan-bolt** [comment] 2021-02-23 04:45
@gbbr Thanks for your help.

I must say, it is a bit sad that the two libraries are not interchangeable. I want to use an OSS that would be hard to swap out opentracing for a more extensible solution, but then I won't be able to tie in those spans with the spans from Datadog, which is what is used to instrument the rest of the application.

I do want to confirm 1 question though: Is it really not possible to implement this method on the tracer https://github.com/opentracing/opentracing-go/blob/master/ext.go#L7?

**Comment by gbbr** [comment] 2021-02-23 10:48
> I do want to confirm 1 question though: Is it really not possible to implement this method on the tracer https://github.com/opentracing/opentracing-go/blob/master/ext.go#L7?

I was actually not aware of that interface! That may indeed change something. We'll have to take some time and look at it.

**Comment by shannontan-bolt** [comment] 2021-02-23 16:06
FWIW, we'd have to consider moving away from the Datadog tracing contributions and towards opentracing contributions if that doesn't work. We've already made the decision to significantly change our architecture using an OSS that supports OpenTracing (https://github.com/temporalio/sdk-go), and the work to get them/us to support Datadog tracing would be more than us just moving away from it completely. That's not to strong-arm you but to more say that I _really_ hope that we get this to work with OpenTracing lol

I did try to give implementing that a shot, but I got confused between DDtrace/OpenTracing spans and contexts lol

**Comment by shannontan-bolt** [comment] 2021-02-23 19:14
Managed to get this working @gbbr! Put up a PR, and I'll be testing it more locally (tested it a few times, but want to make sure its not a fluke). Hopefully, it isn't a fluke though.

One problem though is that this isn't an opt-in functionality, but that means that traces that were previously disconnected are going to be connected. Maybe this is a net-positive, but I can imagine someone saying that this "bug" was a feature to them.

**Comment by shannontan-bolt** [comment] 2021-02-23 19:54
Hmm - I did run into an error now, which makes sense I think. My solution only makes it work if an OpenTracing span is the parent, and all child spans are DD spans. 

It might not work in the opposite direction - a DD span is the parent, and OpenTracing spans are started from it. Still looking.

**Comment by shannontan-bolt** [comment] 2021-02-24 05:08
I believe I understand what is happening now. With my change in #855, I _think_:

- Starting an OpenTracing span will also call `tracer.ContextWithSpan`. Therefore, `opentracing` will set spans for `tracer` spans.
- Starting a `tracer` (DD Tracer) span does *not* call OpenTracing `ContextWithSpan` and therefore, the next time OpenTracing tries to start a Span, it cannot find it and spawns a new one. It also doesn't provide the context as an argument to the StartOption (doesn't exist) so it wouldn't work anyways.

What are the possible options (for me)?
- Accept defeat (joking)
- Swap all of my traces to `opentracing`, especially the ones higher up in the stack (like HTTP client requests). Seems likely, and the easiest to accomplish for us.
- Figure out how to fix the spans, and allow an `tracer.StartSpan...` to also set `opentracing.ContextWithSpan`. Calling this isn't trivial because of import cycles, so it'd require moving around code in order to make this happen.

**Comment by shannontan-bolt** [comment] 2021-02-24 05:26
These are what I have as example code snippets, but they don't work because I can't get an `opentracing.Span` version of the ddtrace.Span.

```
// StartSpanFromContext returns a new span with the given operation name and options. If a span
// is found in the context, it will be used as the parent of the resulting span. If the ChildOf
// option is passed, the span from context will take precedence over it as the parent span.
func StartSpanFromContext(ctx context.Context, operationName string, opts ...StartSpanOption) (Span, context.Context) {
	if ctx == nil {
		// default to context.Background() to avoid panics on Go >= 1.15
		ctx = context.Background()
	}
	if s, ok := SpanFromContext(ctx); ok {
		opts = append(opts, ChildOf(s.Context()))
	}

	s := StartSpan(operationName, opts...)
	ctx = ContextWithSpan(ctx, s)
	
	if opentracing.IsGlobalTracerRegistered() {
		ctx = opentracing.ContextWithSpan(ctx, /* some open tracing version of the span */)
	}

	return s, ctx
}
```

```
func OpenTracingSpanFromDDSpan(ddSpan ddtrace.Span) opentracing.Span {
	return &span{
		Span: ddSpan,
		opentracer: &opentracer{internal.GetGlobalTracer()},
	}
}
```

**Comment by shannontan-bolt** [comment] 2021-02-24 05:27
Not to mention that its just... _weird_

**Comment by shannontan-bolt** [comment] 2021-02-24 05:35
Re-reading this thread better, I feel bad that I didn't closely enough read: https://github.com/DataDog/dd-trace-go/issues/813#issuecomment-759658009. My comments are basically a dupe of that.

Sorry!

**Comment by gbbr** [comment] 2021-03-24 12:02
> One problem though is that this isn't an opt-in functionality, but that means that traces that were previously disconnected are going to be connected. Maybe this is a net-positive, but I can imagine someone saying that this "bug" was a feature to them.

I think that's fine! Seems like a fix to me! 💯 

> Swap all of my traces to opentracing, especially the ones higher up in the stack (like HTTP client requests). Seems likely, and the easiest to accomplish for us.

Is this a possibility for you? What did you end up doing? Can we close this issue?

**Comment by shannontan-bolt** [comment] 2021-03-29 22:58
> Is this a possibility for you? What did you end up doing? Can we close this issue?

I ended up swapping all of my non-leaf traces to OpenTracing. This was a bit annoying, but not the end of the world. I was able to use Datadog traces in places where I knew there wasn't any additional downstream traces (like requests to the DB or to Elasticsearch). Examples that I had to move were manual traces, Gorilla mux router, graphql-gophers.

Feel free to close - I was just waiting to merge the PR.

**Comment by gbbr** [comment] 2021-03-30 09:14
Wonderful. I'm glad it worked out. I guess it does make sense to go with just one system throughout (be that OT or DD). Let's wait for the PR to officially close 🙂

**Comment by davidalpert** [comment] 2021-04-01 17:01
I've missed this issue since the discussion took off so have some catching up to do; apologies if this is out of context or has already been addressed.

It does not make sense to me to have to pick one or the other. That seems like an unrealistic requirement to place on client code.

**Comment by davidalpert** [comment] 2021-04-01 17:39
If I can ask, why is it a hard requirement that the datadog tracing libraries have no reference to the opentracing libraries? 

It seems like the point of the opentracing libraries is to be an implementation-agnostic standard that allows client libraries to plug into whatever tracer the host application happens to be using.

Forcing datadog dependencies throughout the code seems to violate the spirit of that opentracing concept.

**Comment by davidalpert** [comment] 2021-04-01 17:40
When I tried the `span, ok := ddSpan.(opentracing.Span)` type conversion I get an error stating that no type can implement both `gopkg.in/DataDog/dd-trace-go.v1/ddtrace.Span` and `github.com/opentracing/opentracing-go.Span`

**Comment by davidalpert** [comment] 2021-04-01 17:56
seems to me that a datadog span/context should be an opentracing span/context with extra features, thus implying that downstream code can always use it as an opentracing span (if the downstream code does not want or is unable to take a dependency on datadog) and can optionally inspect it to see if it also implements the datadog span/context so that downstream clients who do want to or need to depend on those datadog enhancements can take that extra datadog dependency and opt-in to datadog-specific features.

**Comment by gbbr** [comment] 2021-04-05 08:30
> If I can ask, why is it a hard requirement that the datadog tracing libraries have no reference to the opentracing libraries?

Sure. The idea back then was to avoid dependencies on 3rd party instrumentation systems.

> It seems like the point of the opentracing libraries is to be an implementation-agnostic standard that allows client libraries to plug into whatever tracer the host application happens to be using.
>
> Forcing datadog dependencies throughout the code seems to violate the spirit of that opentracing concept.

I agree, but I'm not entirely sure what you mean by “forcing dependencies” here. I'm suggesting exactly that: to use only Opentracing or only Datadog, not mix both.

Ultimately, we don't want to base our APM system on Opentracing, OpenTelemetry, or OpenCensus, or whatever library comes up in the future. We want to have a solid stand-alone product to guarantee a good, consistent experience for customers, while at the same time making sure to provide as much compatibility as possible with those systems for users that may want to choose them.

Given the latest PR added (#855), I think we can move a lot closer into that direction, to provide even more compatibility. Was that not a satisfactory outcome to you? Based on @shannon-bolt’s answer, I was under the impression that you have already found a satisfactory outcome.

**Comment by alebabai** [comment] 2021-04-05 15:39
#855 really make my day.
After some research about why there is no span hierarchy in my service I found exactly the same conclusion that `ddtrace/opentracing` misses `opentracing.TracerContextWithSpanExtension`.
@shannontan-bolt thanks a lot for the implementation.
Is it possible to somehow speed up the merge, because it also blocks me a bit?

**Comment by gbbr** [comment] 2021-04-19 08:42
#855 was merged.

**Closed by gbbr** 2021-04-19 08:42 UTC
Labels: question
