### ISSUE TITLE
Add Missing support for span propagation

### ISSUE THREAD

**Issue by iyedbennour** [DataDog/dd-trace-go#119] opened 2017-10-25 14:47 UTC
The opentrancing api allows to propagate spans to upstream servers and for upstream servers to extract spans from incoming requests:

    func makeSomeRequest(ctx context.Context) ... {
        if span := opentracing.SpanFromContext(ctx); span != nil {
            httpClient := &http.Client{}
            httpReq, _ := http.NewRequest("GET", "http://myservice/", nil)

            // Transmit the span's TraceContext as HTTP headers on our
            // outbound request.
            opentracing.GlobalTracer().Inject(
                span.Context(),
                opentracing.HTTPHeaders,
                opentracing.HTTPHeadersCarrier(httpReq.Header))

            resp, err := httpClient.Do(httpReq)
            ...
        }
        ...
    }

Extract the span on the upstream server:

    http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
        var serverSpan opentracing.Span
        appSpecificOperationName := ...
        wireContext, err := opentracing.GlobalTracer().Extract(
            opentracing.HTTPHeaders,
            opentracing.HTTPHeadersCarrier(req.Header))
        if err != nil {
            // Optionally record something about err here
        }

        // Create the span referring to the RPC client if available.
        // If wireContext == nil, a root span will be created.
        serverSpan = opentracing.StartSpan(
            appSpecificOperationName,
            ext.RPCServerOption(wireContext))

        defer serverSpan.Finish()

        ctx := opentracing.ContextWithSpan(context.Background(), serverSpan)
        ...
    }

**Comment by palazzem** [comment] 2017-11-08 14:24
Thanks @iyedbennour for pointing that! We're going to support OpenTracing right now, so that issue should be addressed with the new API. Thanks for reporting that!

**Comment by palazzem** [comment] 2017-12-06 02:30
The new OpenTracing compatibility layer, should be enough to handle this case. A recent PR (#132) has been merged and should fix this specific issue. Unfortunately, the problem is still there with the legacy `datadog.Tracer`, but since we're going to deprecate and remove it, there is not reason to worry a lot about it. Better documentation and migration guide will be out when we replace entirely the `Tracer` implementation.

I'm going to close the issue, but feel free to reopen it if you have more questions! Thank you very much!

**Closed by palazzem** 2017-12-06 02:30 UTC
Labels: enhancement
