### ISSUE TITLE
opentracing: diverging from spec

### ISSUE THREAD

**Issue by lwc** [DataDog/dd-trace-go#177] opened 2018-02-08 01:16 UTC
It looks like this library has swapped the meaning of `component` and `operation` versus the opentracing spec.

The [operation](https://github.com/opentracing/specification/blob/master/specification.md#start-a-new-span) should be passed to `StartSpanFromContext`, but instead you're setting it onto a custom tag `resource.name`

The [component](https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table) should be set via e.g. `ext.Component.Set(sp, "http.request")`, but instead you're passing it in as the operation name in `StartSpanFromContext`.

_[EDIT]_
It looks like the opentracing branch is perpetuating this mistake - given that is going to be such a big breaking change anyways perhaps it could be fixed in that branch

**Comment by gbbr** [comment] 2018-02-08 09:34
This should all be fixed with the new release candidate that is in progress. `StartSpanFromContext` will take operation name that is set correctly. I don't see where this is set as a tag called `resource.name` in the code. It is however set as the default resource _unless_ you specify the `resource.name` tag to override.

As for component, it should also be set correctly as a tag, like any other. Do note however that in the case of Datadog it might be best to use the `span.type` tag at least for now.

I'd hold of at least until the release candidate is out before switching to this API as there will be some changes. Afterwards bug reports and issues would be super encouraged, welcomed and helpful to us.

P.S. When you say "opentracing branch", what do you mean? Would be very helpful if your references to code would link to the code itself.

**Comment by lwc** [comment] 2018-02-08 23:18
Hi, thanks for getting back to me.

I was referring to changes in https://github.com/DataDog/dd-trace-go/pull/171 - looks like the release candidate you're talking about.

Would it be helpful for me to test with that branch?

**Comment by gbbr** [comment] 2018-02-09 09:01
> Would it be helpful for me to test with that branch?

No, please don't. Not at all at this point. We are still breaking things and it's work in progress. I'd be very happy if you'd like to help us test once we finalise it, which should be soon.

**Comment by palazzem** [comment] 2018-02-09 11:06
@lwc we will provide a specific branch with all this work merged, so that we can ship a tag as a release candidate. Having your help to try out our new API, would be very appreciated! Also, we know that we're changing a lot of things in our API, but the end goal is to refactor the API so we can reach a very stable 1.0.

This is just to share or mid-term plan. Thank you for your details!

**Comment by palazzem** [comment] 2018-02-26 23:14
**-- Heads-up --**

We've approved (and soon it will be merged) the first step for this migration: https://github.com/DataDog/dd-trace-go/pull/171

It will be part of our feature branch and not `master`, since we're planning to provide the release candidate from this branch. The next step is to update our integrations using this new API. Will provide a new update as soon we're there.

**Comment by lwc** [comment] 2018-04-06 04:25
Hey, just looking over the v1 branch and it looks like this issue still exists:

The OpenTracing spec defines operation name as:
> An operation name, a human-readable string which concisely represents the work done by the Span (for example, an RPC method name, a function name, or the name of a subtask or stage within a larger computation). The operation name should be the most general string that identifies a (statistically) interesting class of Span instances. That is, `get_user` is better than `get_user/314159`.

Your OpenTracing shim passes operation name through to the internal tracer like so: https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/opentracer/tracer.go#L44

Which ends up here: https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/span.go#L29.
This internal version of _Operation Name_ is what the OT spec calls the component:

> The software package, framework, library, or module that generated the associated Span. E.g., "grpc", "django", "JDBI".

This is concerning, as it means the OT implementation in this library has a DataDog flavour that will make interoperability with existing libraries impossible.

**Comment by gbbr** [comment] 2018-04-06 12:44
@lwc could it be that you are confusing things a little bit? I don't think we have a problem with the operation name. What you refer to as component within the OpenTracing spec is in fact what we call "[span type](https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/span.go#L47)" in the Datadog tracer.

If the above is not correct, would you mind being more _specific_ about the problem because maybe it's not clear to me. It would be great to report the bug in the following form:

* Action taken
* Expected behaviour
* Actual behaviour

This will help us better understand what you're trying to do, what you're expecting and what you are getting.

**Comment by gbbr** [comment] 2018-04-06 23:04
@lwc you might also notice that if you _don't_ specifically set a resource name on a span, the operation name is used as the resource internally: https://github.com/DataDog/dd-trace-go/blob/v1/ddtrace/tracer/tracer.go#L206

This is working as you describe, correct?

**Comment by knusbaum** [comment] 2020-02-24 15:55
This issue has gone quite stale, and I don't see anything actionable here.
I am going to close the issue, but please reopen if there's something that needs to be done.

**Closed by knusbaum** 2020-02-24 15:55 UTC
Labels: opentracing
