### ISSUE TITLE
[BUG] compile error after dependency update to version 1.70.1

### ISSUE THREAD

**Issue by mibo-fdc** [DataDog/dd-trace-go#3011] opened 2024-12-05 16:21 UTC
**Version of dd-trace-go**
1.70.1

**Describe what happened:**
After  dependency upgrades this compile error is raised from the package:
gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
# gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer
../../../../../go/pkg/mod/gopkg.in/!data!dog/dd-trace-go.v1@v1.70.1/ddtrace/tracer/tracer.go:339:34: cannot use t.statsd (variable of type "gopkg.in/DataDog/dd-trace-go.v1/internal".StatsdClient) as runtimemetrics.partialStatsdClientInterface value in argument to runtimemetrics.Start: "gopkg.in/DataDog/dd-trace-go.v1/internal".StatsdClient does not implement runtimemetrics.partialStatsdClientInterface (missing method DistributionSamples)

**Describe what you expected:**
No compiler error. It seems to be dependency-related, but the error is from the library itself. I see no combination of dependency updates that causes this.

**Steps to reproduce the issue:**
Dependency update with `go get -u ./...` and `go mod tidy`. After this, the error above occurred in the builds.

**Additional environment details (Version of Go, Operating System, etc.):**
Go 1.23.4, across operation systems (this error also occurs on CI/Linux and on macOS)

**Comment by darccio** [comment] 2024-12-05 16:34
@mibo-fdc Thanks for reaching out. The root cause for this error is `go get -u ./...` upgrading to the latest commit in `github.com/DataDog/go-runtime-metrics-internal` that introduced a breaking change. It's happening also in our [smoke tests](https://github.com/DataDog/dd-trace-go/actions/runs/12166684044/job/33933491287?pr=3007) since today.

A workaround for this is to run `go get github.com/DataDog/go-runtime-metrics-internal@194426bbbd59` in the meantime.

**Comment by mibo-fdc** [comment] 2024-12-05 16:55
Thanks for the fast response. I tried your workaround, but the error stays the same.

I know have 
`github.com/DataDog/go-runtime-metrics-internal v0.0.0-20241106155157-194426bbbd59 // indirect`
in the go.mod as an indirect dependency. This should be enough to fix the issue?

**Comment by darccio** [comment] 2024-12-05 17:10
@mibo-fdc It should be enough. See the screenshot below:

![Image](https://github.com/user-attachments/assets/5ead133b-63ff-45b5-83d8-d3088e0038d8)

Did you run again `go get -u ./...` after pinning the version? Another way to ensure the library is properly pinned is using a `replace` directive like this:

```
go mod edit -replace=github.com/DataDog/go-runtime-metrics-internal=github.com/DataDog/go-runtime-metrics-internal@194426bbbd59
go mod tidy
```

I did it locally and it also worked (after running again `go get -u ./...`):

![Image](https://github.com/user-attachments/assets/ff9cc58f-3d22-4eab-89b0-549c4e0d92d8)

**Comment by mibo-fdc** [comment] 2024-12-05 17:20
No, I did not update the version again after the go get.
However, with the version pinning, it works. Thanks for the help!

**Comment by felixge** [comment] 2024-12-06 11:26
This should be fixed now. See [this comment](https://github.com/DataDog/go-runtime-metrics-internal) for more details and how we're planning to prevent this kind of issue from appearing again in the future. Sorry for the trouble this caused 🙇

**Closed by felixge** 2024-12-06 11:26 UTC
Labels: bug
