### ISSUE TITLE
[BUG] Newly introduced database/sql metrics do not send over Unix sockets

### ISSUE THREAD

**Issue by jared-mackey** [DataDog/dd-trace-go#2677] opened 2024-04-30 14:44 UTC
**Version of dd-trace-go**
1.63.0

**Describe what happened:**

https://github.com/DataDog/dd-trace-go/issues/2303#issuecomment-2076000564

**Describe what you expected:**
New metrics to work over Unix sockets

**Steps to reproduce the issue:**

https://github.com/DataDog/dd-trace-go/issues/2303#issuecomment-2076000564

cc @mtoffl01

**Comment by mtoffl01** [comment] 2024-05-02 20:52
Hey @jared-mackey ,
> It does not read or use DD_DOGSTATSD_URL like I would expect it to.
`DD_DOGSTATSD_URL` is **not** a valid config option for dd-trace-go (Note: Confusingly, it _is_ valid for other Datadog tracers such as dd-trace-py). See here: https://docs.datadoghq.com/tracing/trace_collection/library_config/go, only `DD_DOGSTATSD_PORT` is available for configuration via env var.
To have total control over the dogstatsd address, you'd need the tracer config option [WithDogstatsdAddress](https://pkg.go.dev/gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer#WithDogstatsdAddress).

Regardless of the env var's significance to the tracer, it should still work if you pass that env var as a value to the tracer start option, like in your example `tracer.WithDogstatsdAddress(os.Getenv("DD_DOGSTATSD_URL"))`. A few questions:

1. When you use just the `DD_DOGSTATSD_URL` env var, can you confirm whether you receive any runtime metrics or tracer health metrics (these should be prefixed with `datadog.tracer`, entries like `datadog.tracer.started` and `datadog.tracer.spans_started`). With this config, I'd guess you're missing all dogstatsd payloads from the tracer, not just db stats
2. Can you confirm the WithDogstatsdAddress option does not work? What is the behavior you're seeing in the logs for this specific case? I could not reproduce this on my side.

**Comment by mtoffl01** [comment] 2024-05-08 19:48
@jared-mackey , 
> I’d be happy to share exact code samples over a support ticket if that’s helpful. Just let me know.
Please do! When you open the support ticket, please be sure to reference this github issue so that the support rep who takes the case will have this context, and bubble it up to us.

**Comment by darccio** [comment] 2024-07-31 14:48
Closing this issue because it was handled through support ticket.

**Closed by darccio** 2024-07-31 14:48 UTC
Labels: bug
