### ISSUE TITLE
contrib/jmoiron/sqlx: returns duplicate traces and "driver error: skip fast-path"

### ISSUE THREAD

**Issue by art-ivaschenko** [DataDog/dd-trace-go#270] opened 2018-06-28 12:41 UTC
When enabling sql/sqlx integration, making db queries sends multiple query traces duplicates. The following error is also persistently present: 
`*errors.errorString: driver: skip fast-path; continue as if unimplemented`
Below is the result of single request: there are 3 duplicates of the same DB query for both of queries, error appeared two times as well. 
<img width="1236" alt="screen shot 2018-06-28 at 2 21 26 pm" src="https://user-images.githubusercontent.com/4533121/42034602-3ba575ba-7ae9-11e8-9ef4-d92d04418b09.png">

UPDATE: Actually I just found out why I get 2 queries - one is for Prepare and one is for Query. But in code it is not reflected. The question about error is still open though. Possible solution is to change `resource = query` to `resource = resource + " " + query` in contrib/database/sql/driver.go in the following method: 
```go
func (tp *traceParams) newChildSpanFromContext(ctx context.Context, resource string, query string) ddtrace.Span {
	name := fmt.Sprintf("%s.query", tp.driverName)
	span, _ := tracer.StartSpanFromContext(ctx, name,
		tracer.SpanType(ext.AppTypeDB),
		tracer.ServiceName(tp.config.serviceName),
	)
	if query != "" {
		resource = query
	}
	span.SetTag(ext.ResourceName, resource)
	for k, v := range tp.meta {
		span.SetTag(k, v)
	}
	return span
}

**Comment by gbbr** [comment] 2018-06-28 13:53
Thanks for bringing this up. I've recently experienced this myself.

From [`(database/sql/driver).ErrSkip`](https://golang.org/pkg/database/sql/driver/#ErrSkip):
```go
// ErrSkip may be returned by some optional interfaces' methods to
// indicate at runtime that the fast path is unavailable and the sql
// package should continue as if the optional interface was not
// implemented. ErrSkip is only supported where explicitly
// documented.
var ErrSkip = errors.New("driver: skip fast-path; continue as if unimplemented")
```
This tells me that this isn't actually an error, but just a signal towards the caller that 
the interface doesn't implement this method and an alternative is available.

I think we should simply cancel recording these calls when `ErrSkip` is returned. Before doing that however, we should make sure that a second call always follows.

**Comment by art-ivaschenko** [comment] 2018-06-28 14:46
Thanks for reply. I actually found out where its coming from. So there is parameter in sql called `interpolateParams` which is False by default. According to official docs: 

_If interpolateParams is true, placeholders (?) in calls to db.Query() and db.Exec() are interpolated into a single query string with given parameters. This reduces the number of roundtrips, since the driver has to prepare a statement, execute it with given parameters and close the statement again with interpolateParams=false._

So by default it goes like prepare-execute-close, so it makes 3 rounds to execute the query, in other words it uses prepared statements. We actually see 4 traces for one query, because the first one is the one that is being cancelled after ErrSkip is thrown, and then it goes to Prepare -> Execute -> Close. But when I set interpolateParams=true in DB DSN as an extra argument, it shows exactly one query which it executes. 

Here is where it comes from (go-sql-driver/mysql/connection.go): 
```
func (mc *mysqlConn) query(query string, args []driver.Value) (*textRows, error) {
	if mc.closed.IsSet() {
		errLog.Print(ErrInvalidConn)
		return nil, driver.ErrBadConn
	}
	if len(args) != 0 {
		if !mc.cfg.InterpolateParams {
			return nil, driver.ErrSkip
		}
		// try client-side prepare to reduce roundtrip
		prepared, err := mc.interpolateParams(query, args)
		if err != nil {
			return nil, err
		}
		query = prepared
	}
```
As seen above if InterpolateParams is False (which it is by default) it will throw ErrSkip, and will do roundtrip at server side, which will result in what we see now: Query (which doesn't go far because ErrSkip is thrown) -> Error, Prepare -> Query-> Close. If we set InterpolateParams to True, then it will do prepare at client-side, and we will see only one final query in DataDog, and ErrSkip will not be thrown. 

More reading on this:
http://go-database-sql.org/prepared.html
https://stackoverflow.com/questions/37683218/golang-sql-drivers-prepare-statement

**Comment by gbbr** [comment] 2018-06-28 15:44
> UPDATE: Actually I just found out why I get 2 queries - one is for Prepare and one is for Query. 

I understand. I just saw your edit to your original post. It seems that it is indeed valid to have two entries in the resource here. I would say that no change is needed here. However, I definitely understand your frustration with seeing that. 

> Possible solution is to change `resource = query` to `resource = resource + " " + query` in contrib/database/sql/driver.go

Unfortunately the solution you are suggesting is not viable because it would break time series history for everybody and interfere with other analysis tools that we have.

I think the best compromise here would be to potentially add another tag on the span specifying the type of operation that happened, in your case "Prepare" vs "Query".

**Comment by gbbr** [comment] 2018-06-28 15:45
Leaving this as `won't fix` for now, but the issue remains open for others to chip in. If this turns out to affect many people and become cumbersome, we might consider adding in the extra tag or making further changes. Thanks for being patient.

**Comment by dcormier** [comment] 2018-07-09 13:49
Having `ErrSkip` treated as a real error is problematic in my environment. It makes it difficult to spot actual errors in the APM console since this one happens so frequently.

**Comment by gbbr** [comment] 2018-09-28 10:13
Instead of just making these traces green (OK), I've made a PR to remove them completely, as they would only serve as duplicates and would have no real instrumentation value. Does this sound like a good solution to you guys? Feel free to take a look at #336

**Comment by gbbr** [comment] 2018-09-28 10:32
@art-ivaschenko and @dcormier could you please provide a basic snippet that helps reproduce this problem? I'd like to make sure my PR fixes it before considering merging.

**Comment by gbbr** [comment] 2018-10-01 15:47
@dcormier thanks a lot! This helped me reproduce the problem and confirm that my PR fixes it.

**Comment by gbbr** [comment] 2018-10-01 15:47
Please feel free to open a new issue if this breaks anything. I'll add it into the next release.

**Closed** 2018-10-01 15:47 UTC
Labels: ack, integrations

**Comment by speza** [comment] 2020-08-18 07:47
Sorry to kick this issue back up a little bit, appreciate its been a couple of years (happy to raise a new issue if required).

We're currently using sqlx and DD tracing and still see duplicate traces. Obviously the reasoning here with these being multiple calls to the DB due to prepared statements.

We use sqlx `GetContext(...)` which ends up with 4 calls to `tryTrace(...)`. I end up with the following three traces...
1 `SELECT * from X` << prepare
2 `SELECT * from X` << query
3 `Close`

1 & 2 are obviously duplicates with 1 being the `Prepare` and 2 being `Query`. I'm not sure what the intention is here, but there is no way to tell them apart from the traces.

Are there any plans to add an extra tag for the 'resource' in the `tryTrace` method or something similar so we can tell these traces apart?

**Comment by gbbr** [comment] 2020-08-18 08:57
It would be nice to set a tag on the prepare statement, or even name the operation differently (e.g. `<driver>.prepare`) but I'm not sure if that's easily achievable. Do you have any implementation ideas?

**Comment by speza** [comment] 2020-08-18 14:43
Is there a chance that modifying the operation name could break this for people who are already using it?

Adding a new tag is an option.

So there is the `tryTrace(...)` in `contrib/database/sql/conn.go` method, which sets the span resource.name as `resource`.

Problem is that `resource` is mutated to equal the `query` value if a query is provided. On a prepared statement, query is passed in but also a resource of `Prepare` is.

```go
span, _ := tracer.StartSpanFromContext(ctx, name, opts...)
if query != "" {
	resource = query
}
span.SetTag(ext.ResourceName, resource)
```

One option could be to add a span tag before that mutation occurs? It still wouldn't be that clear from the trace overview in the Datadog dashboard.

**Comment by gbbr** [comment] 2020-08-19 07:23
> Is there a chance that modifying the operation name could break this for people who are already using it?

That's true. You're right. We shouldn't do that.

I think one approach is to add a new type in the code, something like:

```go
// queryType defines the type of query being executed.
type queryType string

const (
    queryTypeQuery queryType = "Query"
    queryTypePing = "Ping"
    queryTypePrepare = "Prepare"
    // ...
)
```

Then we would modify `tryTrace` to take a `queryType` as the second parameter. This would then go onto the span as `sql.query_type` and one would be able to tell more details about what happened.

What do you think?

**Comment by speza** [comment] 2020-08-19 07:42
Yes, I think something like that would work nicely @gbbr. Happy to submit a PR if you like?

**Comment by gbbr** [comment] 2020-08-19 12:23
Please go ahead! Thanks!
