### ISSUE TITLE
proposal: contrib/Shopify/sarama: support sarama.ConsumerGroup

### ISSUE THREAD

**Issue by mingrammer** [DataDog/dd-trace-go#699] opened 2020-07-30 06:30 UTC
We are using `sarama.ConsumerGroup` of `Shopify/sarama` package, but there are only for `Consumer` and `PartitionConsumer`.

It would be good if the `ConsumerGroup` wrapper also is supported.

Thank you.

**Comment by gbbr** [comment] 2020-07-30 10:46
Is it easy to add? Would you be interested in doing the work?

**Comment by mingrammer** [comment] 2020-07-31 07:46
Yap. I'll try to implement it!

**Comment by adw1n** [comment] 2020-09-21 01:01
It's a duplicate of https://github.com/DataDog/dd-trace-go/issues/552

**Comment by knusbaum** [comment] 2020-09-24 00:15
Thanks, @adw1n.
Closing this as a duplicate of #552 

@mingrammer we can continue on that ticket.

**Closed by knusbaum** 2020-09-24 00:15 UTC
Labels: integrations, proposal
