### ISSUE TITLE
[BUG] dd-trace-go states that it is an Apache license, but it pulls in DataDog/datadog-agent which includes eBPF code which is GPL 2.0 licensed

### ISSUE THREAD

**Issue by powerbill** [DataDog/dd-trace-go#2678] opened 2024-05-01 16:46 UTC
**Version of dd-trace-go**
v1.63.1 

**Describe what happened:**
dd-trace-go states that it is an Apache license, but it pulls in DataDog/datadog-agent which includes eBPF code which is GPL 2.0 licensed

**Describe what you expected:**
[BUG] dd-trace-go uses only Apache licensed code.

**Steps to reproduce the issue:**
NA

**Additional environment details (Version of Go, Operating System, etc.):**

**Comment by eliottness** [comment] 2024-05-02 09:41
👋 Hello @powerbill, thanks for warning us about it, we are currently investigating. I will let you know how this goes.

**Comment by eliottness** [comment] 2024-05-02 14:28
Hello again @powerbill.

I have confirmed the fact if some code in a repo is under GPL 2.0 does not mean that the whole repo has to be under GPL 2.0. The bpf helpers we are using are indeed under the GPL 2.0 license because they call some kernel code but they are explicitly baked into a separate object file in the agent so they can retain a different license.

I am gonna go ahead and close this issue. Feel free to reopen it if you have more questions. 👍

**Closed by eliottness** 2024-05-02 14:28 UTC
Labels: bug

**Comment by powerbill** [comment] 2024-05-06 22:50
@eliottness I'm not referring to the datadog agent, I'm referring to the use in dd-trace-go which will be included in downstream go code. I do not think that this can be re-opened except by you.

**Comment by powerbill** [comment] 2024-05-06 22:52
See [this line](https://github.com/DataDog/dd-trace-go/blob/3a426cad6b642bc0dab36d49c02f8e09b40529e5/ddtrace/tracer/tracer.go#L274) for a specific example of dd-agent/pkg/obfuscate being pulled into dd-trace-go
