### ISSUE TITLE
proposal: add back ForceFlush

### ISSUE THREAD

**Issue by lonnblad** [DataDog/dd-trace-go#337] opened 2018-09-30 11:59 UTC
Hey

We run a lot of our code in AWS Lambda and since there is currently not an integration with AWS X-Ray, we run a Datadog agent as an internal service which our lambdas would push all their traces to.

We were using v0.6.1 until last week when we started to upgrade to v1.3.0, which is when we noticed that ForceFlush was made private.

We are using ForceFlush at the end of every lambda handler execution to be sure the traces are flushed to the agent before the handler finishes, but with v1.3.0 this is no longer possible.

This is why I would propose to add a `ForceFlush` to the tracer pkg, include `ForceFlush` in the `Tracer interface` and make `func (t *tracer) forceFlush()` public again.

This is my dd-trace-go [solution](https://github.com/DataDog/dd-trace-go/commit/6fc37d75ab1952b1f9e5632903bea7543b234233).

An [example](https://play.golang.org/p/h5geNfVrusp) of an AWS Lambda function.

BR Fredrik Lönnblad

**Comment by lonnblad** [comment] 2018-10-01 14:48
Hi, yes I experience loss of traces and I can actually see in the debug
prints that the traces fail to be sent to the agent.
Also, I am not sure `tracer.Stop` can be called in a good way from the main
method with aws-lambda-go.

Do you know if you (Datadog) have tried this with AWS Lambda in go?

BR
Fredrik

**Comment by lonnblad** [comment] 2018-10-01 15:48
Hi, yes I experience loss of traces and I can actually see in the debug
printouts that the traces fail to be sent to the agent.
Also, I am not sure `tracer.Stop` can be called in a good way from the main
method with aws-lambda-go.

Do you know if you (Datadog) have tried this with AWS Lambda in go?

BR
Fredrik

**Comment by gbbr** [comment] 2018-10-01 15:51
> yes I experience loss of traces and I can actually see in the debug
printouts that the traces fail to be sent to the agent.
Also, I am not sure tracer.Stop can be called in a good way from the main
method with aws-lambda-go.

Why can you not call it "in a good way" from the main function? Also, can you please paste the error messages you are seeing? It sounds unusual for this to happen. I'd rather focus on addressing that rather than adding extra API methods.

> Do you know if you (Datadog) have tried this with AWS Lambda in go?

I will look into that.

If you can share any code that could help me reproduce the problem, that would be super useful.

**Comment by lonnblad** [comment] 2018-10-01 16:16
What I could try is to add a graceful shutdown to the main function as I would do with a normal container, I will try and see what happens, however my view of AWS Lambda is that background processes is not really how they are supposed to work.

Another thing is that with this type of solution I build dependencies to AWS Lambda underlying architecture which is not a part of their official documentation and therefor open to change at any time without me knowing.

**Comment by gbbr** [comment] 2018-10-01 17:30
I am happy to consider changes to the API if they are valid. I'd first like to make sure one is needed before considering it. It might be just that there is a different solution to the one you currently have which would provide better instrumentation without hacky workarounds.

I'll be able to help a lot better if you provide a code snippet illustrating the problem. Let me know how your trial goes.

**Comment by lonnblad** [comment] 2018-10-01 18:03
Here is some code.
https://play.golang.org/p/u9mgRLTPb_U

I could previously see that the latest trace was never sent, so when trigger the Lambda once, I didn't get a trace, when triggering it again, I could see one trace.

I got another error now however.
```
[ TRACE ] 2018-10-01 17:32:11 ERROR (agent.go:226) - skipping trace with root too far in past, root:{enlight.translate handler.execute handler.execute 9000451317791109542 9000451317791109542 0 1538414996518193688 297649181 0 map[system.pid:7 region:eu-west-1 env:sandbox] map[] }
```

**Comment by lonnblad** [comment] 2018-10-01 18:14
I have a hard time knowing if `tracer.Stop()` ever gets called when the Lambda container terminates, so the trial with listening on an `os.Signal` was not really successful.

**Comment by gbbr** [comment] 2018-10-01 18:29
> I could previously see that the latest trace was never sent, so when trigger the Lambda once, I didn't get a trace, when triggering it again, I could see one trace.

This sounds more like a sampling decision. Not all traces get sent to Datadog and they are subject to sampling. If you wish to ensure a trace gets sampled you can use the `ext.SamplingPriority` tag. Just add this tag to the `rootSpan` in your example above:

```go
rootSpan, ctx := tracer.StartSpanFromContext(ctx, "handler.execute", tracer.Tag(ext.SamplingPriority, ext.UserKeep))
```
Read more a about priority sampling [here](https://docs.datadoghq.com/tracing/getting_further/trace_sampling_and_storage/#priority-sampling-for-distributed-tracing).

> so we could start and stop the tracer in the handler instead without the risk of concurrency issues with the global tracer.

You can safely start and stop the tracer as much as you like, it is thread-safe by design. But I don't think that is necessary. I think everything is already working as it should, except perhaps you were not familiar with how sampling works.

Do note however that if you introduce sampling priority this will affect your quotas. If the volume on these traces is low, then this isn't something to worry about.

Try it out and let me know. I think we can close this issue once you confirm that this solves your problem. Traces are flushed automatically at most [every 2 seconds](https://github.com/DataDog/dd-trace-go/blob/cbae6123912c36ec2aacc8b26d245836debe31fc/ddtrace/tracer/tracer.go#L49) and if your application exits gracefully, any leftovers are flushed too. If your application does not exit gracefully, this is something to address on your end.

**Comment by lonnblad** [comment] 2018-10-01 18:47
I will look in to sampling priority, have some reading up to do there, don't think that was the issue, but not an expert on this.

I believe we can close this, everything seems to be working while running manual test at least.

If I start the tracer in two different threads and stops it one, that wouldn't affect the second thread?

**Comment by gbbr** [comment] 2018-10-01 18:51
You can only have one tracer started at one time, no matter how many times you call `Start`. When calling `Stop` (no matter in what thread), it will stop any actively running tracer. This is not a good approach because it could cause a race condition in the sense that calling `Stop` in one thread could cause the tracer to be stopped in the other thread after the `Start` call and you could lose any traces.

By race condition here I don't mean a panic, I just mean a logical race condition.

Feel free to write again if you have any more questions or problems. I hope my help supplies enough information to get a satisfying result.

**Closed by gbbr** 2018-10-01 18:51 UTC
Labels: proposal

**Comment by lonnblad** [comment] 2018-10-01 18:57
That was what I meant with concurrency issue, since, now I start and stop the tracer in the handler, which wouldn't have worked if multiple instances of the handler code would have been executed in parallel.
